CREATE TABLE `users` (
	`id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`pseudo` VARCHAR(50) NOT NULL,
	`userName` VARCHAR(50) NOT NULL,
	`inputEmail` VARCHAR(50) NOT NULL,
	`inputPassword` VARCHAR(50) NOT NULL,
	`inputPhoneNumber` VARCHAR(50) NULL DEFAULT NULL,
	`checkNewsLetter` VARCHAR(50) NULL DEFAULT NULL,
	CONSTRAINT PRIMARY KEY (id)
);