-- MySQL Script generated by MySQL Workbench
-- Wed Jan 20 11:31:20 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema MVC
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema MVC
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `MVC` DEFAULT CHARACTER SET utf8mb4 ;
USE `MVC` ;

-- -----------------------------------------------------
-- Table `MVC`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MVC`.`users` ;

CREATE TABLE IF NOT EXISTS `MVC`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `pseudo` VARCHAR(50) NOT NULL,
  `username` VARCHAR(50) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `password` VARCHAR(50) NOT NULL,
  `phoneNumber` VARCHAR(50) NULL,
  `newsLetter` VARCHAR(50) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `uniqueUser` (`username` ASC) INVISIBLE,
  UNIQUE INDEX `uniqueEmail` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
